INSERT INTO SERVICE (SERVICE_NAME, SERVICE_INFO) VALUES ('OrderService', 'Order Service');
INSERT INTO SERVICE (SERVICE_NAME, SERVICE_INFO) VALUES ('ShipService', 'Shipping Service');
INSERT INTO SERVICE (SERVICE_NAME, SERVICE_INFO) VALUES ('ReservationService', 'Reservation Service');
INSERT INTO SERVICE (SERVICE_NAME, SERVICE_INFO) VALUES ('ConfigService', 'Config Service');
INSERT INTO SERVICE (SERVICE_NAME, SERVICE_INFO) VALUES ('BackupService', 'Backup Service');
INSERT INTO SERVICE (SERVICE_NAME, SERVICE_INFO) VALUES ('CompareService', 'Compare Service');

INSERT INTO CUSTOMER (CUSTOMER_NAME, CUSTOMER_INFO) VALUES ('John', 'Demo User John');
INSERT INTO CUSTOMER (CUSTOMER_NAME, CUSTOMER_INFO) VALUES ('Mike', 'Demo User Mike');
INSERT INTO CUSTOMER (CUSTOMER_NAME, CUSTOMER_INFO) VALUES ('Tim', 'Demo User Tim');
INSERT INTO CUSTOMER (CUSTOMER_NAME, CUSTOMER_INFO) VALUES ('Jacky', 'Demo User Jacky');
INSERT INTO CUSTOMER (CUSTOMER_NAME, CUSTOMER_INFO) VALUES ('Willy', 'Demo User Willy');
INSERT INTO CUSTOMER (CUSTOMER_NAME, CUSTOMER_INFO) VALUES ('Ken', 'Demo User Ken');

INSERT INTO SERVICE_CUSTOMER(SERVICE_ID, CUSTOMER_ID) VALUES(1, 1);
INSERT INTO SERVICE_CUSTOMER(SERVICE_ID, CUSTOMER_ID) VALUES(2, 2);
INSERT INTO SERVICE_CUSTOMER(SERVICE_ID, CUSTOMER_ID) VALUES(3, 3);
INSERT INTO SERVICE_CUSTOMER(SERVICE_ID, CUSTOMER_ID) VALUES(4, 4);
INSERT INTO SERVICE_CUSTOMER(SERVICE_ID, CUSTOMER_ID) VALUES(5, 5);
INSERT INTO SERVICE_CUSTOMER(SERVICE_ID, CUSTOMER_ID) VALUES(6, 6);
