CREATE TABLE SERVICE(
  SERVICE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  SERVICE_NAME VARCHAR(64) NOT NULL,
  SERVICE_INFO VARCHAR(256) NULL
);

CREATE TABLE CUSTOMER(
  CUSTOMER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  CUSTOMER_NAME VARCHAR(64) NOT NULL,
  CUSTOMER_INFO VARCHAR(256) NULL
);

CREATE TABLE SERVICE_CUSTOMER (
  SERVICE_ID BIGINT,
  CUSTOMER_ID BIGINT,
  FOREIGN KEY (SERVICE_ID) REFERENCES SERVICE(SERVICE_ID),
  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
  PRIMARY KEY (SERVICE_ID, CUSTOMER_ID)
);